[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
restartPolicyType = "on_failure"

[service]
internal_port = 3000
auto_stop_machines = false
auto_start_machines = true

[[services]]
protocol = "tcp"
internal_port = 3000
